---
title: "EDA_Course_Project_1"
author: "Jeff Hamilton"
date: "9/8/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, warning=FALSE, message=FALSE}
library(tidyverse)
library(lubridate)
library(patchwork)
```

## Get Data
```{r data, warning=FALSE}
hpc <- read_delim("~/RProjects/EDA_Course_Project_1/data/household_power_consumption.txt", delim = ";")
```

```{r clean_data}
hpc$Date <- dmy(hpc$Date)
```

```{r subset}
hpc_small <- hpc %>% filter(Date == "2007-02-01" | Date == "2007-02-02")
```

```{r plot-1}
hpc_small %>% ggplot(aes(x=Global_active_power)) + geom_histogram(fill = "red", color = "black", breaks = seq(0,6,by=0.5)) + labs(x ="Global Active Power (kilowatts)", y = "Frequency")
```


```{r plot-2}
hpc_small$dt <- as.POSIXct(paste(hpc_small$Date, hpc_small$Time), format="%Y-%m-%d %H:%M:%S")

hpc_small %>% ggplot(aes(x=dt, y = Global_active_power)) + geom_line() + labs(x =NULL, y = "Global Active Power (kilowatts)") + scale_x_datetime(date_breaks = "day", date_labels = "%a")

```


```{r plot-3}

hpc_small %>% select(7:10) %>% pivot_longer(1:3, names_to = "sub_metering", values_to = "value") %>% ggplot(aes(x=dt, y = value, color = sub_metering)) + geom_line() + labs(x =NULL, y = "Energy sub metering") + scale_x_datetime(date_breaks = "day", date_labels = "%a") + theme(legend.position = c(0.9, 0.9), legend.title = element_blank())

```

```{r plot-4}
#use patchwork, create the four plots 

p1 <- hpc_small %>% ggplot(aes(x=dt, y = Global_active_power)) + geom_line() + labs(x =NULL, y = "Global Active Power (kilowatts)") + scale_x_datetime(date_breaks = "day", date_labels = "%a")

p2 <- hpc_small %>% select(7:10) %>% pivot_longer(1:3, names_to = "sub_metering", values_to = "value") %>% ggplot(aes(x=dt, y = value, color = sub_metering)) + geom_line() + labs(x =NULL, y = "Energy sub metering") + scale_x_datetime(date_breaks = "day", date_labels = "%a") + theme(legend.position = c(0.85, 0.8), legend.title = element_blank(),legend.text=element_text(size=6), legend.key.size = unit(1,"line"))

p3 <- hpc_small %>% ggplot(aes(x=dt, y = Voltage)) + geom_line() + labs(x ="datetime") + scale_x_datetime(date_breaks = "day", date_labels = "%a")

p4 <- hpc_small %>% ggplot(aes(x=dt, y = Global_reactive_power)) + geom_line() + labs(x ="datetime") + scale_x_datetime(date_breaks = "day", date_labels = "%a")

plot4 <- (p1 + p3)/(p2 + p4)
plot4
```

